dist: trusty
sudo: false
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang-7
      - lld-7
      - libc++-7-dev
      - libc++abi-7-dev
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-trusty-7

matrix:
  include:
  - env: c_compiler=clang-7 cxx_compiler=clang++-7
    compiler: clang

script:
  - ${c_compiler} -v && ${cxx_compiler} -v && cmake --version && make --version
  - export CC=${c_compiler}
  - export CXX=${cxx_compiler}
  - cmake -DUNIX=ON CMakeLists.txt
  - make --keep-going VERBOSE=1
  - ./Introspector-generator
  
notfications:
  email: false
